window.F300_DATA = {
  "updated": "28 Aug 2026",
  "standings": [
    {
      "position": 1,
      "driver": "Gary Woodward",
      "number": 55,
      "rounds": 3,
      "wins": 0,
      "podiums": 1,
      "bestFinal": 2,
      "points": 442
    },
    {
      "position": 2,
      "driver": "James Price",
      "number": 8,
      "rounds": 3,
      "wins": 1,
      "podiums": 1,
      "bestFinal": 1,
      "points": 427
    },
    {
      "position": 3,
      "driver": "Ryan Martin",
      "number": 17,
      "rounds": 3,
      "wins": 2,
      "podiums": 2,
      "bestFinal": 1,
      "points": 415
    },
    {
      "position": 4,
      "driver": "Jack Reeve",
      "number": 4,
      "rounds": 2,
      "wins": 0,
      "podiums": 1,
      "bestFinal": 3,
      "points": 305
    },
    {
      "position": 5,
      "driver": "Nye Cortizo-White",
      "number": 16,
      "rounds": 2,
      "wins": 0,
      "podiums": 1,
      "bestFinal": 3,
      "points": 292
    },
    {
      "position": 6,
      "driver": "Jason Merritt",
      "number": 11,
      "rounds": 3,
      "wins": 0,
      "podiums": 0,
      "bestFinal": 7,
      "points": 189
    },
    {
      "position": 7,
      "driver": "Guy Hefford",
      "number": 50,
      "rounds": 2,
      "wins": 0,
      "podiums": 1,
      "bestFinal": 2,
      "points": 188
    },
    {
      "position": 8,
      "driver": "Jason Cooper",
      "number": 69,
      "rounds": 1,
      "wins": 0,
      "podiums": 0,
      "bestFinal": 4,
      "points": 149
    },
    {
      "position": 9,
      "driver": "Oliver Warner",
      "number": 46,
      "rounds": 1,
      "wins": 0,
      "podiums": 1,
      "bestFinal": 2,
      "points": 137
    },
    {
      "position": 10,
      "driver": "Jack Goodyer",
      "number": 116,
      "rounds": 1,
      "wins": 0,
      "podiums": 1,
      "bestFinal": 3,
      "points": 130
    },
    {
      "position": 11,
      "driver": "Nicholas Cleere",
      "number": 44,
      "rounds": 1,
      "wins": 0,
      "podiums": 0,
      "bestFinal": 9,
      "points": 128
    },
    {
      "position": 12,
      "driver": "Matt Cater",
      "number": 64,
      "rounds": 1,
      "wins": 0,
      "podiums": 0,
      "bestFinal": 5,
      "points": 118
    },
    {
      "position": 13,
      "driver": "Lilly Brame",
      "number": 43,
      "rounds": 1,
      "wins": 0,
      "podiums": 0,
      "bestFinal": 8,
      "points": 100
    },
    {
      "position": 14,
      "driver": "Brett Knapp",
      "number": 12,
      "rounds": 1,
      "wins": 0,
      "podiums": 0,
      "bestFinal": "N/A",
      "points": 52
    }
  ],
  "calendar": [
    {
      "round": 1,
      "track": "Lydd",
      "date": "9th–10th May",
      "status": "Complete"
    },
    {
      "round": 2,
      "track": "Whilton Mill",
      "date": "30th–31st May",
      "status": "Complete"
    },
    {
      "round": null,
      "track": "Clay Pigeon",
      "date": "4th–5th July",
      "status": "Cancelled"
    },
    {
      "round": 3,
      "track": "Wombwell",
      "date": "8th–9th August",
      "status": "Complete"
    },
    {
      "round": 4,
      "track": "Lydd",
      "date": "6th September",
      "status": "Upcoming"
    },
    {
      "round": null,
      "track": "Llandow",
      "date": "12th–13th September",
      "status": "Cancelled"
    },
    {
      "round": 5,
      "track": "Lydd",
      "date": "11th October",
      "status": "Upcoming"
    },
    {
      "round": null,
      "track": "Fulbeck",
      "date": "10th–11th October",
      "status": "Cancelled"
    }
  ],
  "raceResults": [
    {
      "round": 1,
      "track": "Lydd",
      "driver": "Ryan Martin",
      "h1Result": "3",
      "h1Points": 31,
      "h2Result": "1",
      "h2Points": 36,
      "h3Result": "1",
      "h3Points": 36,
      "finalResult": "1",
      "finalPoints": 72,
      "weekendTotal": 175,
      "h1Lap": "36.909",
      "h2Lap": "36.961",
      "h3Lap": "37.125",
      "finalLap": "36.891",
      "weekendBest": "36.891",
      "notes": ""
    },
    {
      "round": 1,
      "track": "Lydd",
      "driver": "Guy Hefford",
      "h1Result": "4",
      "h1Points": 30,
      "h2Result": "3",
      "h2Points": 31,
      "h3Result": "2",
      "h3Points": 33,
      "finalResult": "2",
      "finalPoints": 66,
      "weekendTotal": 160,
      "h1Lap": "37.577",
      "h2Lap": "37.175",
      "h3Lap": "37.098",
      "finalLap": "37.103",
      "weekendBest": "37.098",
      "notes": ""
    },
    {
      "round": 1,
      "track": "Lydd",
      "driver": "James Price",
      "h1Result": "2",
      "h1Points": 33,
      "h2Result": "2",
      "h2Points": 33,
      "h3Result": "4",
      "h3Points": 30,
      "finalResult": "6",
      "finalPoints": 56,
      "weekendTotal": 152,
      "h1Lap": "36.863",
      "h2Lap": "36.712",
      "h3Lap": "36.971",
      "finalLap": "36.985",
      "weekendBest": "36.712",
      "notes": ""
    },
    {
      "round": 1,
      "track": "Lydd",
      "driver": "Jack Reeve",
      "h1Result": "1",
      "h1Points": 36,
      "h2Result": "4",
      "h2Points": 30,
      "h3Result": "6",
      "h3Points": 28,
      "finalResult": "3",
      "finalPoints": 62,
      "weekendTotal": 156,
      "h1Lap": "36.823",
      "h2Lap": "37.239",
      "h3Lap": "37.326",
      "finalLap": "37.134",
      "weekendBest": "36.823",
      "notes": ""
    },
    {
      "round": 1,
      "track": "Lydd",
      "driver": "Jason Cooper",
      "h1Result": "5",
      "h1Points": 29,
      "h2Result": "5",
      "h2Points": 29,
      "h3Result": "3",
      "h3Points": 31,
      "finalResult": "4",
      "finalPoints": 60,
      "weekendTotal": 149,
      "h1Lap": "37.650",
      "h2Lap": "37.315",
      "h3Lap": "37.262",
      "finalLap": "37.224",
      "weekendBest": "37.224",
      "notes": ""
    },
    {
      "round": 1,
      "track": "Lydd",
      "driver": "Gary Woodward",
      "h1Result": "6",
      "h1Points": 28,
      "h2Result": "6",
      "h2Points": 28,
      "h3Result": "5",
      "h3Points": 29,
      "finalResult": "7",
      "finalPoints": 54,
      "weekendTotal": 139,
      "h1Lap": "37.730",
      "h2Lap": "38.046",
      "h3Lap": "37.688",
      "finalLap": "37.791",
      "weekendBest": "37.688",
      "notes": ""
    },
    {
      "round": 1,
      "track": "Lydd",
      "driver": "Nye Cortizo-White",
      "h1Result": "7",
      "h1Points": 27,
      "h2Result": "7",
      "h2Points": 27,
      "h3Result": "7",
      "h3Points": 27,
      "finalResult": "5",
      "finalPoints": 58,
      "weekendTotal": 139,
      "h1Lap": "38.311",
      "h2Lap": "38.125",
      "h3Lap": "38.330",
      "finalLap": "38.624",
      "weekendBest": "38.125",
      "notes": ""
    },
    {
      "round": 1,
      "track": "Lydd",
      "driver": "Nicholas Cleere",
      "h1Result": "8",
      "h1Points": 26,
      "h2Result": "8",
      "h2Points": 26,
      "h3Result": "8",
      "h3Points": 26,
      "finalResult": "9",
      "finalPoints": 50,
      "weekendTotal": 128,
      "h1Lap": "39.722",
      "h2Lap": "39.974",
      "h3Lap": "39.752",
      "finalLap": "42.521",
      "weekendBest": "39.722",
      "notes": ""
    },
    {
      "round": 1,
      "track": "Lydd",
      "driver": "Brett Knapp",
      "h1Result": "9",
      "h1Points": 25,
      "h2Result": "9",
      "h2Points": 25,
      "h3Result": "DNF",
      "h3Points": 2,
      "finalResult": "DNS",
      "finalPoints": 0,
      "weekendTotal": 52,
      "h1Lap": "39.425",
      "h2Lap": "39.773",
      "h3Lap": "-",
      "finalLap": "-",
      "weekendBest": "39.425",
      "notes": ""
    },
    {
      "round": 1,
      "track": "Lydd",
      "driver": "Jason Merritt",
      "h1Result": "10",
      "h1Points": 24,
      "h2Result": "DNS",
      "h2Points": 0,
      "h3Result": "DNS",
      "h3Points": 0,
      "finalResult": "DNS",
      "finalPoints": 0,
      "weekendTotal": 24,
      "h1Lap": "38.920",
      "h2Lap": "-",
      "h3Lap": "-",
      "finalLap": "-",
      "weekendBest": "38.920",
      "notes": ""
    },
    {
      "round": 1,
      "track": "Lydd",
      "driver": "Lilly Brame",
      "h1Result": "11",
      "h1Points": 23,
      "h2Result": "DNS",
      "h2Points": 0,
      "h3Result": "9",
      "h3Points": 25,
      "finalResult": "8",
      "finalPoints": 52,
      "weekendTotal": 100,
      "h1Lap": "42.381",
      "h2Lap": "-",
      "h3Lap": "41.408",
      "finalLap": "41.633",
      "weekendBest": "41.408",
      "notes": ""
    },
    {
      "round": 2,
      "track": "Whilton Mill",
      "driver": "James Price",
      "h1Result": "5",
      "h1Points": 29,
      "h2Result": "3",
      "h2Points": 31,
      "h3Result": "1",
      "h3Points": 36,
      "finalResult": "1",
      "finalPoints": 72,
      "weekendTotal": 168,
      "h1Lap": "47.008",
      "h2Lap": "46.840",
      "h3Lap": "46.364",
      "finalLap": "46.389",
      "weekendBest": "46.364",
      "notes": ""
    },
    {
      "round": 2,
      "track": "Whilton Mill",
      "driver": "Oliver Warner",
      "h1Result": "1",
      "h1Points": 36,
      "h2Result": "DNF",
      "h2Points": 2,
      "h3Result": "2",
      "h3Points": 33,
      "finalResult": "2",
      "finalPoints": 66,
      "weekendTotal": 137,
      "h1Lap": "46.541",
      "h2Lap": "46.694",
      "h3Lap": "46.101",
      "finalLap": "46.365",
      "weekendBest": "46.101",
      "notes": ""
    },
    {
      "round": 2,
      "track": "Whilton Mill",
      "driver": "Jack Goodyer",
      "h1Result": "DNF",
      "h1Points": 2,
      "h2Result": "1",
      "h2Points": 36,
      "h3Result": "4",
      "h3Points": 30,
      "finalResult": "3",
      "finalPoints": 62,
      "weekendTotal": 130,
      "h1Lap": "46.983",
      "h2Lap": "46.295",
      "h3Lap": "46.676",
      "finalLap": "46.381",
      "weekendBest": "46.295",
      "notes": ""
    },
    {
      "round": 2,
      "track": "Whilton Mill",
      "driver": "Jack Reeve",
      "h1Result": "2",
      "h1Points": 33,
      "h2Result": "5",
      "h2Points": 29,
      "h3Result": "7",
      "h3Points": 27,
      "finalResult": "4",
      "finalPoints": 60,
      "weekendTotal": 149,
      "h1Lap": "47.425",
      "h2Lap": "47.822",
      "h3Lap": "47.771",
      "finalLap": "46.661",
      "weekendBest": "46.661",
      "notes": ""
    },
    {
      "round": 2,
      "track": "Whilton Mill",
      "driver": "Matt Cater",
      "h1Result": "3",
      "h1Points": 31,
      "h2Result": "DNS",
      "h2Points": 0,
      "h3Result": "5",
      "h3Points": 29,
      "finalResult": "5",
      "finalPoints": 58,
      "weekendTotal": 118,
      "h1Lap": "47.401",
      "h2Lap": "-",
      "h3Lap": "47.354",
      "finalLap": "47.671",
      "weekendBest": "47.354",
      "notes": ""
    },
    {
      "round": 2,
      "track": "Whilton Mill",
      "driver": "Gary Woodward",
      "h1Result": "4",
      "h1Points": 30,
      "h2Result": "4",
      "h2Points": 30,
      "h3Result": "6",
      "h3Points": 28,
      "finalResult": "6",
      "finalPoints": 56,
      "weekendTotal": 144,
      "h1Lap": "47.608",
      "h2Lap": "47.307",
      "h3Lap": "47.569",
      "finalLap": "47.854",
      "weekendBest": "47.307",
      "notes": ""
    },
    {
      "round": 2,
      "track": "Whilton Mill",
      "driver": "Jason Merritt",
      "h1Result": "7",
      "h1Points": 27,
      "h2Result": "6",
      "h2Points": 28,
      "h3Result": "8",
      "h3Points": 26,
      "finalResult": "7",
      "finalPoints": 54,
      "weekendTotal": 135,
      "h1Lap": "49.213",
      "h2Lap": "49.018",
      "h3Lap": "49.845",
      "finalLap": "50.131",
      "weekendBest": "49.018",
      "notes": ""
    },
    {
      "round": 2,
      "track": "Whilton Mill",
      "driver": "Ryan Martin",
      "h1Result": "DNF",
      "h1Points": 2,
      "h2Result": "2",
      "h2Points": 33,
      "h3Result": "3",
      "h3Points": 31,
      "finalResult": "DNS",
      "finalPoints": 0,
      "weekendTotal": 66,
      "h1Lap": "47.118",
      "h2Lap": "47.103",
      "h3Lap": "46.708",
      "finalLap": "-",
      "weekendBest": "46.708",
      "notes": ""
    },
    {
      "round": 2,
      "track": "Whilton Mill",
      "driver": "Guy Hefford",
      "h1Result": "6",
      "h1Points": 28,
      "h2Result": "DNS",
      "h2Points": 0,
      "h3Result": "DNS",
      "h3Points": 0,
      "finalResult": "DNS",
      "finalPoints": 0,
      "weekendTotal": 28,
      "h1Lap": "47.557",
      "h2Lap": "-",
      "h3Lap": "-",
      "finalLap": "-",
      "weekendBest": "47.557",
      "notes": ""
    },
    {
      "round": 3,
      "track": "Wombwell",
      "driver": "James Price",
      "h1Result": "1",
      "h1Points": 36,
      "h2Result": "3",
      "h2Points": 31,
      "h3Result": "1",
      "h3Points": 36,
      "finalResult": "DNF",
      "finalPoints": 4,
      "weekendTotal": 107,
      "h1Lap": "32.702",
      "h2Lap": "32.536",
      "h3Lap": "32.266",
      "finalLap": "32.866",
      "weekendBest": "32.266",
      "notes": ""
    },
    {
      "round": 3,
      "track": "Wombwell",
      "driver": "Ryan Martin",
      "h1Result": "2",
      "h1Points": 33,
      "h2Result": "1",
      "h2Points": 36,
      "h3Result": "2",
      "h3Points": 33,
      "finalResult": "1",
      "finalPoints": 72,
      "weekendTotal": 174,
      "h1Lap": "32.584",
      "h2Lap": "32.663",
      "h3Lap": "32.558",
      "finalLap": "32.654",
      "weekendBest": "32.558",
      "notes": ""
    },
    {
      "round": 3,
      "track": "Wombwell",
      "driver": "Nye Cortizo-White",
      "h1Result": "3",
      "h1Points": 31,
      "h2Result": "4",
      "h2Points": 30,
      "h3Result": "4",
      "h3Points": 30,
      "finalResult": "3",
      "finalPoints": 62,
      "weekendTotal": 153,
      "h1Lap": "34.152",
      "h2Lap": "33.682",
      "h3Lap": "33.649",
      "finalLap": "33.339",
      "weekendBest": "33.339",
      "notes": ""
    },
    {
      "round": 3,
      "track": "Wombwell",
      "driver": "Jason Merritt",
      "h1Result": "4",
      "h1Points": 30,
      "h2Result": "DNS",
      "h2Points": 0,
      "h3Result": "DNS",
      "h3Points": 0,
      "finalResult": "DNS",
      "finalPoints": 0,
      "weekendTotal": 30,
      "h1Lap": "34.138",
      "h2Lap": "-",
      "h3Lap": "-",
      "finalLap": "-",
      "weekendBest": "34.138",
      "notes": ""
    },
    {
      "round": 3,
      "track": "Wombwell",
      "driver": "Gary Woodward",
      "h1Result": "5",
      "h1Points": 29,
      "h2Result": "2",
      "h2Points": 33,
      "h3Result": "3",
      "h3Points": 31,
      "finalResult": "2",
      "finalPoints": 66,
      "weekendTotal": 159,
      "h1Lap": "34.235",
      "h2Lap": "32.670",
      "h3Lap": "32.532",
      "finalLap": "32.613",
      "weekendBest": "32.532",
      "notes": ""
    }
  ]
};
